// GENERATED FILE -- do not edit by hand.
//
// Source: BepInEx/interop/Assembly-CSharp.dll, enums eBuffType / TalentDefine.Type /
// TalentDefine.TriggerTiming / eTalentCondType. Regenerate with:
//     python _dpsm_work/gen_talent_names.py
// (Hand-typing ~560 enum members would guarantee transcription errors, so the tables are parsed straight
//  out of the interop decompile. The Chinese strings are TRANSLATIONS OF THE ENUM MEMBER NAMES, not text
//  extracted from the game; the game own status vocabulary -- 暗闇/狂气/恐怖/即死/石化/冻结 -- is used so
//  this agrees with the wiki.)
//
// WHY THIS EXISTS
// TalentData.TalentType is a UNION of two id spaces, which cost a round trip to discover:
//     >= 1000  -> TalentDefine.Type  (actions: 1005 DamageUp, 1015 AdditionalAttack, 1016 PenetrationAttack,
//                                    1019 DirectAttackRate, 1021 DirectHeal, 1064 FixedDamage, 1093 DotDamage...)
//     1..999   -> eBuffType          (parameter and STATUS changes: 6 PowerRatePlus, 86 PenetrationRateActualPlus,
//                                    508 Stun, 509 Petrifaction, 510 Poison, 511 KnockBack, 514 Burn,
//                                    515 Frozen, 516 Darkness, 517 Madness, 518 Fear, 519 Death...)
// Before this table those ids printed as "t511"/"t519", i.e. a battle log was unreadable exactly where it
// mattered most -- which status a unit is able to apply.
namespace DpsMeter;

internal static class TalentNames
{
	/// <summary>TalentDefine.Type (id >= 1000): the action a talent performs.</summary>
	internal static string ActionType(int v)
	{
		switch (v)
		{
			case 0: return "None";
			case 1000: return "BuffTypeSeparateNum";
			case 1001: return "Hate";
			case 1002: return "ModeChange";
			case 1003: return "LifeLink";
			case 1004: return "AddTalent";
			case 1005: return "与伤害+";
			case 1006: return "被伤害-";
			case 1007: return "伤害吸收";
			case 1008: return "伤害反射";
			case 1009: return "ChangeSkill";
			case 1010: return "ChangeSpecialSkill";
			case 1011: return "Comeback";
			case 1012: return "TokenSummon";
			case 1013: return "连射";
			case 1014: return "多重射击";
			case 1015: return "追加攻击";
			case 1016: return "贯通攻击";
			case 1017: return "EngagementAttack";
			case 1018: return "ResistWeather";
			case 1019: return "直接攻击倍率";
			case 1020: return "直接攻击实值";
			case 1021: return "直接回复";
			case 1022: return "SummonRestrict";
			case 1023: return "ChangeHitType";
			case 1024: return "DamageField";
			case 1025: return "ChangePlayerExpRate";
			case 1026: return "ChangeGoldRate";
			case 1027: return "PlayEffectByPosition";
			case 1028: return "PlayEffectByPoint";
			case 1029: return "PlayEffectByCharacter";
			case 1030: return "OpenEntryGroup";
			case 1031: return "ChangeWeather";
			case 1032: return "攻击回复";
			case 1033: return "SummonSlave";
			case 1034: return "ResurrectionSlave";
			case 1035: return "SetCharacterSpecialAction";
			case 1036: return "CloseEntryGroup";
			case 1037: return "ComebackTimeShortening";
			case 1038: return "SkillWaitTimeShortening";
			case 1039: return "播放攻击";
			case 1040: return "Immortal";
			case 1041: return "复活";
			case 1042: return "护盾";
			case 1043: return "MoveFlyBan";
			case 1044: return "直接攻击攻击力";
			case 1045: return "ChangeAttackMotion";
			case 1046: return "AttackLockOnTarget";
			case 1047: return "ChangeLife";
			case 1048: return "ActingInvincible";
			case 1049: return "SpecialRange";
			case 1050: return "ResetExistenceTime";
			case 1051: return "ResetAttackCount";
			case 1052: return "ResetDestroyCount";
			case 1053: return "PlayAuraEffect";
			case 1054: return "MissileReflection";
			case 1055: return "DirectAttackRateIgnoreAbility";
			case 1056: return "DirectAttackActualIgnoreAbility";
			case 1057: return "DirectAttackPowerIgnoreAbility";
			case 1058: return "无视回避";
			case 1059: return "不屈";
			case 1060: return "伤害代偿";
			case 1061: return "AutoSkillRandom";
			case 1062: return "OverSkillRandom";
			case 1063: return "外部参数";
			case 1064: return "固定伤害";
			case 1065: return "PlusPrivateGeneralCounter";
			case 1066: return "MinusPrivateGeneralCounter";
			case 1067: return "DirectAttackRateEnableAttacker";
			case 1068: return "DirectAttackActualEnableAttacker";
			case 1069: return "DirectAttackPowerEnableAttacker";
			case 1070: return "PlusEnemyGeneralCounter";
			case 1071: return "MinusEnemyGeneralCounter";
			case 1072: return "AddTalentLottery";
			case 1073: return "CharacterGiantGrowth";
			case 1074: return "MissileGiantGrowth";
			case 1075: return "MissileShot";
			case 1076: return "计时开始";
			case 1077: return "计时重置";
			case 1078: return "概率追加";
			case 1079: return "击退演出";
			case 1080: return "无效化所有异常";
			case 1081: return "PlayDeath";
			case 1082: return "BomSkillStockUnlimited";
			case 1083: return "BomSpecialSkillStockRecovery";
			case 1084: return "Teleport";
			case 1085: return "SelfDamageReflection";
			case 1086: return "ScreenShake";
			case 1087: return "BomSkillStockRecovery";
			case 1088: return "BomSkillStockModifierPlus";
			case 1089: return "BomSkillStockMaxModifierPlus";
			case 1090: return "PlayEffectByRangeActivatePoint";
			case 1091: return "SubAttackBan";
			case 1092: return "AttackDataForceUpdate";
			case 1093: return "持续伤害";
			case 1094: return "回复反转";
			case 1095: return "天赋复制";
			case 2000: return "BattleSeparateNum";
			case 2001: return "StartPhase";
			case 2002: return "AppOmen";
			case 2003: return "PlayBossDirection";
			case 2004: return "PlayDirection";
			case 2005: return "WaitGame";
			case 2006: return "ChangeBgm";
			case 2007: return "ChangeFieldTexture";
			case 2008: return "CallTalkEvent";
			case 2009: return "OpenHelpWindow";
			case 2010: return "PopupGameWindow";
			case 2011: return "TutorialMessage";
			case 2012: return "TutorialButtonCoverEnable";
			case 2013: return "TutorialButtonCoverDisable";
			case 2014: return "SetTimeLimit";
			case 2015: return "SuddenlyWin";
			case 2016: return "SuddenlyLose";
			case 2017: return "ChangeUnitLookAt";
			case 2018: return "UnitPlacement";
			case 2019: return "EnableGodRay";
			case 2020: return "EnablePlacementObject";
			case 2021: return "DropItem";
			case 2022: return "ChangePlayerMotion";
			case 2023: return "ChangeEnemyMotion";
			case 2024: return "AttackPlayerToEnemy";
			case 2025: return "AttackEnemyToPlayer";
			case 2026: return "DrawMissile";
			case 2027: return "ScrollMapReturn";
			case 2028: return "ScrollMapByPoint";
			case 2029: return "ScrollMapByPosition";
			case 2030: return "ScrollMapByThisPoint";
			case 2031: return "ZoomMap";
			case 2032: return "SetShrinkFlag";
			case 2033: return "Max";
			default: return "";
		}
	}

	/// <summary>eBuffType (id 1..999): the parameter/status a talent changes.</summary>
	internal static string BuffType(int v)
	{
		switch (v)
		{
			case 0: return "None";
			case 1: return "耐久%+";
			case 2: return "耐久%-";
			case 3: return "耐久+";
			case 4: return "耐久-";
			case 5: return "耐久=";
			case 6: return "攻击力%+";
			case 7: return "攻击力%-";
			case 8: return "攻击力+";
			case 9: return "攻击力-";
			case 10: return "攻击力=";
			case 11: return "物防%+";
			case 12: return "物防%-";
			case 13: return "物防+";
			case 14: return "物防-";
			case 15: return "物防=";
			case 16: return "魔防%+";
			case 17: return "魔防%-";
			case 18: return "魔防+";
			case 19: return "魔防-";
			case 20: return "魔防=";
			case 21: return "移速%+";
			case 22: return "移速%-";
			case 23: return "移速+";
			case 24: return "移速-";
			case 25: return "移速=";
			case 26: return "攻速%+";
			case 27: return "攻速%-";
			case 28: return "攻速+";
			case 29: return "攻速-";
			case 30: return "攻速=";
			case 31: return "攻隔%+";
			case 32: return "攻隔%-";
			case 33: return "攻隔+";
			case 34: return "攻隔-";
			case 35: return "攻隔=";
			case 36: return "射程%+";
			case 37: return "射程%-";
			case 38: return "射程+";
			case 39: return "射程-";
			case 40: return "射程=";
			case 41: return "攻击次数+";
			case 42: return "攻击次数-";
			case 43: return "攻击次数=";
			case 44: return "格挡数+";
			case 45: return "格挡数-";
			case 46: return "格挡数=";
			case 47: return "目标数+";
			case 48: return "目标数-";
			case 49: return "目标数=";
			case 50: return "回复上限+";
			case 51: return "回复上限-";
			case 52: return "回复上限=";
			case 53: return "仇恨+";
			case 54: return "仇恨-";
			case 55: return "仇恨=";
			case 56: return "范围仇恨+";
			case 57: return "范围仇恨-";
			case 58: return "范围仇恨=";
			case 59: return "据点仇恨+";
			case 60: return "据点仇恨-";
			case 61: return "据点仇恨=";
			case 62: return "自然回复率";
			case 63: return "自然回复量";
			case 64: return "持续伤害率";
			case 65: return "持续伤害量";
			case 66: return "投射物=";
			case 67: return "范围形状=";
			case 68: return "目标类型=";
			case 69: return "攻击类型=";
			case 70: return "攻击排序=";
			case 71: return "格挡需要=";
			case 72: return "自动技能充能=";
			case 73: return "技能首待%+";
			case 74: return "技能首待%-";
			case 75: return "觉醒反射+";
			case 76: return "命中率+";
			case 77: return "命中率-";
			case 78: return "会心率+";
			case 79: return "会心率-";
			case 80: return "会心伤害率+";
			case 81: return "会心伤害率-";
			case 82: return "会心降低率+";
			case 83: return "会心降低率-";
			case 84: return "会心伤害降低率+";
			case 85: return "会心伤害降低率-";
			case 86: return "贯通率+";
			case 87: return "贯通率-";
			case 88: return "回复率+";
			case 89: return "回复率-";
			case 90: return "回避率+";
			case 91: return "回避率-";
			case 92: return "副攻击=";
			case 93: return "副目标数+";
			case 94: return "副目标数-";
			case 95: return "副目标数=";
			case 96: return "OS充能=";
			case 97: return "攻击过滤=";
			case 98: return "爆弹技能无限";
			case 99: return "守护范围仇恨+";
			case 100: return "守护范围仇恨-";
			case 101: return "守护范围仇恨=";
			case 102: return "附加属性=";
			case 103: return "会心率上限+";
			case 400: return "眩晕耐性+";
			case 401: return "眩晕耐性-";
			case 402: return "眩晕蓄积耐性+";
			case 403: return "眩晕蓄积耐性-";
			case 404: return "石化耐性+";
			case 405: return "石化耐性-";
			case 406: return "石化蓄积耐性+";
			case 407: return "石化蓄积耐性-";
			case 408: return "毒耐性+";
			case 409: return "毒耐性-";
			case 410: return "毒伤害耐性+";
			case 411: return "毒伤害耐性-";
			case 412: return "击退耐性+";
			case 413: return "击退耐性-";
			case 414: return "火傷耐性+";
			case 415: return "火傷耐性-";
			case 416: return "冻结耐性+";
			case 417: return "冻结耐性-";
			case 418: return "暗闇耐性+";
			case 419: return "暗闇耐性-";
			case 420: return "狂气耐性+";
			case 421: return "狂气耐性-";
			case 422: return "恐怖耐性+";
			case 423: return "恐怖耐性-";
			case 424: return "即死耐性+";
			case 425: return "即死耐性-";
			case 426: return "时停耐性+";
			case 427: return "时停耐性-";
			case 428: return "眩晕耐性=";
			case 429: return "石化耐性=";
			case 430: return "毒耐性=";
			case 431: return "击退耐性=";
			case 432: return "火傷耐性=";
			case 433: return "冻结耐性=";
			case 434: return "暗闇耐性=";
			case 435: return "狂气耐性=";
			case 436: return "恐怖耐性=";
			case 437: return "即死耐性=";
			case 438: return "时停耐性=";
			case 450: return "基础状态耐性+";
			case 451: return "基础状态耐性-";
			case 452: return "移速耐性+";
			case 453: return "移速耐性-";
			case 454: return "攻速耐性+";
			case 455: return "攻速耐性-";
			case 456: return "攻隔耐性+";
			case 457: return "攻隔耐性-";
			case 458: return "基础状态耐性=";
			case 459: return "移速耐性=";
			case 460: return "攻速耐性=";
			case 461: return "攻隔耐性=";
			case 462: return "击退速度";
			case 463: return "击退类型";
			case 464: return "击退速度";
			case 465: return "毒伤害";
			case 466: return "火傷伤害";
			case 500: return "ParamBuffMax";
			case 501: return "时停";
			case 502: return "飞行";
			case 503: return "隐蔽";
			case 504: return "煽动";
			case 505: return "顿帧";
			case 506: return "束缚";
			case 507: return "技能封印";
			case 508: return "眩晕";
			case 509: return "石化";
			case 510: return "毒";
			case 511: return "击退";
			case 512: return "治疗禁止";
			case 513: return "附魔禁止";
			case 514: return "火傷";
			case 515: return "冻结";
			case 516: return "暗闇";
			case 517: return "狂气";
			case 518: return "恐怖";
			case 519: return "即死";
			case 520: return "目标数溢出重复";
			case 521: return "攻击次数转目标数";
			case 900: return "ParamStatusBuffMax";
			case 901: return "时停无效";
			case 902: return "飞行无效";
			case 903: return "隐蔽无效";
			case 904: return "煽动无效";
			case 905: return "顿帧无效";
			case 906: return "束缚无效";
			case 907: return "技能封印无效";
			case 908: return "眩晕无效";
			case 909: return "石化无效";
			case 910: return "毒无效";
			case 911: return "击退无效";
			case 912: return "治疗禁止无效";
			case 913: return "附魔禁止无效";
			case 914: return "火傷无效";
			case 915: return "冻结无效";
			case 916: return "暗闇无效";
			case 917: return "狂气无效";
			case 918: return "恐怖无效";
			case 919: return "即死无效";
			case 1000: return "StatusParamBuffMax";
			default: return "";
		}
	}

	/// <summary>TalentDefine.TriggerTiming: when the talent is evaluated.</summary>
	internal static string Timing(int v)
	{
		switch (v)
		{
			case 0: return "None";
			case 1: return "Passive";
			case 2: return "Attack";
			case 3: return "Block";
			case 4: return "Summon";
			case 5: return "Sortie";
			case 6: return "Evacuate";
			case 7: return "Dead";
			case 8: return "Lost";
			case 9: return "Comeback";
			case 10: return "Revival";
			case 11: return "SkillStart";
			case 12: return "SkillFinish";
			case 13: return "SpecialSkillStart";
			case 14: return "SpecialSkillFinish";
			case 15: return "OverChargeSkillStart";
			case 16: return "OverChargeSkillFinish";
			case 17: return "PlayAttack1";
			case 18: return "Destroy";
			case 19: return "BackAttack";
			case 20: return "Critical";
			case 21: return "FirstLaunchAttack";
			case 22: return "LaunchAttack";
			case 23: return "BattleStart";
			case 24: return "Result";
			case 25: return "Touch";
			case 26: return "Status";
			case 27: return "Organize";
			case 28: return "Possession";
			case 29: return "BattleEvent";
			case 30: return "EarlyPassive";
			case 31: return "EvacuateSlaveNoDestroy";
			case 32: return "EvacuateSlaveDestroy";
			case 33: return "PlayAttack2";
			case 34: return "PlayAttack2End";
			case 35: return "AttackStart";
			case 36: return "AttackEnd";
			case 37: return "TeleportAttack";
			case 38: return "AutoSkill1Start";
			case 39: return "AutoSkill1Finish";
			case 40: return "AutoSkill2Start";
			case 41: return "AutoSkill2Finish";
			case 42: return "OverSkillStart";
			case 43: return "OverSkillFinish";
			case 44: return "SpecialSkillHit";
			case 45: return "SpecialAbilityAttack";
			case 46: return "BlockIgnoreHeal";
			case 47: return "ExternalSheetMax";
			case 48: return "Manual";
			case 49: return "CheckWeather";
			default: return "";
		}
	}

	/// <summary>eTalentCondType: the predicate of a structured trigger condition.</summary>
	internal static string Cond(int v)
	{
		switch (v)
		{
			case 0: return "None";
			case 1: return "IsBlocking";
			case 2: return "IsMoving";
			case 3: return "IsVanguard";
			case 4: return "IsRearguard";
			case 5: return "IsGround";
			case 6: return "IsFly";
			case 7: return "IsPhysicalAttack";
			case 8: return "IsMagicAttack";
			case 9: return "IsIgnoreAttack";
			case 10: return "IsHealAttack";
			case 11: return "IsFriendTeam";
			case 12: return "IsEnemyTeam";
			case 13: return "IsToken";
			case 14: return "IsOwnerToken";
			case 15: return "IsPlayer";
			case 16: return "IsEnemy";
			case 17: return "IsBoss";
			case 18: return "IsBom";
			case 19: return "IsCitadel";
			case 20: return "IsOwner";
			case 21: return "IsBlockedByOwner";
			case 22: return "IsAttributeSameAsOwner";
			case 23: return "IsOwnerEnchantTarget";
			case 24: return "IsBattleCharacterEnable";
			case 25: return "IsWaitMotion";
			case 26: return "IsIndomitable";
			case 27: return "IsStun";
			case 28: return "IsPetrifaction";
			case 29: return "IsPoison";
			case 30: return "IsBurn";
			case 31: return "IsFrozen";
			case 32: return "IsDarkness";
			case 33: return "IsMadness";
			case 34: return "IsFear";
			case 35: return "IsSkillActivated";
			case 36: return "IsSpecialSkillActivated";
			case 37: return "IsOverChargeSkillActivated";
			case 38: return "IsAwakingCompleted";
			case 39: return "IsInBattleArea";
			case 40: return "IsInCitadelArea";
			case 41: return "IsInFriendCitadelArea";
			case 42: return "IsInEnemyCitadelArea";
			case 43: return "IsFriendPlayer";
			case 44: return "IsFriendToken";
			case 1000: return "Move";
			case 1001: return "Weather";
			case 1002: return "Attribute";
			case 1003: return "Rarity";
			case 1004: return "Tribe";
			case 1005: return "Gender";
			case 1006: return "JobSystemId";
			case 1007: return "JobId";
			case 1008: return "CharaId";
			case 1009: return "SkillNo";
			case 1010: return "SkillLevel";
			case 1011: return "NormalSkillLevel";
			case 1012: return "SpecialSkillLevel";
			case 1013: return "Trait";
			case 1014: return "Faction";
			case 1015: return "EnemyId";
			case 1016: return "BomId";
			case 2000: return "HpRate";
			case 2001: return "ExistenceTime";
			case 2002: return "WaitTime";
			case 2003: return "AttackCount";
			case 2004: return "ContinuousAttackCount";
			case 2005: return "DeathCount";
			case 2006: return "ComebackCount";
			case 2007: return "RevivalCount";
			case 2008: return "DestroyCount";
			case 2009: return "TotalExistenceTime";
			case 2010: return "TotalAttackCount";
			case 2011: return "TotalDestroyCount";
			case 2012: return "TotalSkillCount";
			case 2013: return "ExtraIndex";
			case 2014: return "AliveSlaveCount";
			case 2015: return "AttackTargetCount";
			case 2016: return "BlockCount";
			case 2017: return "PrivateGeneralCounter";
			case 2018: return "IsDeadAllVanguard";
			case 2019: return "AutoSkill1Level";
			case 2020: return "AutoSkill2Level";
			case 2021: return "OverSkillLevel";
			case 2022: return "IsAutoSkill1Activated";
			case 2023: return "IsAutoSkill2Activated";
			case 2024: return "IsOverSkillActivated";
			case 2025: return "IsSelfTokenGranted";
			case 2026: return "WaitMotionFrame";
			case 2027: return "UnitSkinId";
			case 2028: return "BomSkillLevel";
			case 2029: return "BomSpecialSkillLevel";
			case 2030: return "IsUniqueTokenGranted";
			case 2031: return "NowMoveSpeed";
			case 2032: return "AliveFriendVanguardCount";
			case 2033: return "AliveEnemyVanguardCount";
			case 2034: return "IsDeadFriendAllVanguard";
			case 2035: return "IsDeadEnemyAllVanguard";
			case 3000: return "QuestCategory";
			case 3001: return "QuestId";
			case 3002: return "TimeLimit";
			case 3003: return "MapType";
			case 4000: return "IsTutorial";
			case 4001: return "IsScenarioPlay";
			case 4002: return "IsNotCleared";
			case 5000: return "SortieTribe";
			case 5001: return "SortieJobSystem";
			case 5002: return "SortieJob";
			case 5003: return "SortieChara";
			case 5004: return "SortieOwnerToken";
			case 5005: return "ElapsedTime1";
			case 5006: return "ElapsedTime2";
			case 5007: return "ElapsedTime3";
			case 5008: return "TriggeredByProbability";
			case 5009: return "SpecialActionElapsedTime";
			case 10000: return "Exclusive";
			case 40000: return "GiveTalent";
			case 40001: return "SkillTalent";
			case 40002: return "Limit";
			case 40003: return "TouchArea";
			case 40004: return "TotalLimit";
			case 40005: return "GiveLottery";
			case 9999998: return "GiveLotterySeriesParameter";
			default: return "";
		}
	}
}
